-- Run this in Supabase SQL editor for the CMS/admin pages.

create table if not exists public.cms_blocks (
  id text primary key,
  page text not null,
  label text not null,
  type text not null default 'textarea',
  value text not null default '',
  style jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.site_settings (
  id text primary key default 'main',
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  date text default '',
  day text default '',
  month text default '',
  year integer default extract(year from now()),
  type text default 'press-releases',
  image_url text default '',
  source_url text default '',
  is_featured boolean default false,
  is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  image_url text not null,
  year integer default extract(year from now()),
  type text default 'Photo',
  is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.careers (
  id bigint generated by default as identity primary key,
  title text not null,
  department text default '',
  location text default '',
  type text default 'Full Time',
  description text default '',
  responsibilities text[] default '{}',
  requirements text[] default '{}',
  application_email text default 'hr@jetama.com.my',
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.cms_blocks enable row level security;
alter table public.site_settings enable row level security;
alter table public.news enable row level security;
alter table public.gallery enable row level security;
alter table public.careers enable row level security;

-- Public read access for website display.
drop policy if exists "public read cms" on public.cms_blocks;
create policy "public read cms" on public.cms_blocks for select using (true);
drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings for select using (true);
drop policy if exists "public read published news" on public.news;
create policy "public read published news" on public.news for select using (is_published = true);
drop policy if exists "public read published gallery" on public.gallery;
create policy "public read published gallery" on public.gallery for select using (is_published = true);
drop policy if exists "public read active careers" on public.careers;
create policy "public read active careers" on public.careers for select using (is_active = true);

-- Authenticated admin write access.
drop policy if exists "admin write cms" on public.cms_blocks;
create policy "admin write cms" on public.cms_blocks for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "admin write settings" on public.site_settings;
create policy "admin write settings" on public.site_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "admin write news" on public.news;
create policy "admin write news" on public.news for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "admin write gallery" on public.gallery;
create policy "admin write gallery" on public.gallery for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "admin write careers" on public.careers;
create policy "admin write careers" on public.careers for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
