create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  date text,
  day text,
  month text,
  year int,
  type text not null default 'press-releases',
  image_url text,
  source_url text,
  is_featured boolean default false,
  is_published boolean default true,
  sort_order int default 10,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.careers (
  id bigint generated by default as identity primary key,
  title text not null,
  department text,
  location text,
  type text,
  description text not null,
  responsibilities text[] default '{}',
  requirements text[] default '{}',
  application_email text default 'hr@jetama.com.my',
  closing_date text,
  is_active boolean default true,
  sort_order int default 10,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  caption text,
  image_url text not null,
  category text default 'corporate',
  date text,
  is_published boolean default true,
  sort_order int default 10,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.cms_blocks (
  id text primary key,
  page text not null,
  label text not null,
  type text default 'textarea',
  value text not null,
  style jsonb default '{}',
  is_published boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.site_settings (
  id int primary key default 1,
  settings jsonb not null,
  updated_at timestamptz default now()
);

insert into public.site_settings (id, settings)
values (
  1,
  '{"primaryColor":"#005AAA","secondaryColor":"#35B24A","accentColor":"#F5A623","darkColor":"#052B4F","fontFamily":"Poppins, sans-serif","navRadius":"18px","cardRadius":"28px","buttonRadius":"999px","heroHeight":"560px","logoScale":"1","motionIntensity":"normal","backgroundMode":"soft-gradient"}'::jsonb
)
on conflict (id) do nothing;

-- Storage bucket for uploaded CMS images.
insert into storage.buckets (id, name, public)
values ('website-assets', 'website-assets', true)
on conflict (id) do nothing;

-- Public read policies. Adjust write policies if you want stricter admin-only rules.
alter table public.news enable row level security;
alter table public.careers enable row level security;
alter table public.gallery enable row level security;
alter table public.cms_blocks enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "public read news" on public.news;
create policy "public read news" on public.news for select using (true);
drop policy if exists "public read careers" on public.careers;
create policy "public read careers" on public.careers for select using (true);
drop policy if exists "public read gallery" on public.gallery;
create policy "public read gallery" on public.gallery for select using (true);
drop policy if exists "public read cms blocks" on public.cms_blocks;
create policy "public read cms blocks" on public.cms_blocks for select using (true);
drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings" on public.site_settings for select using (true);

drop policy if exists "authenticated manage news" on public.news;
create policy "authenticated manage news" on public.news for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage careers" on public.careers;
create policy "authenticated manage careers" on public.careers for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage gallery" on public.gallery;
create policy "authenticated manage gallery" on public.gallery for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage cms blocks" on public.cms_blocks;
create policy "authenticated manage cms blocks" on public.cms_blocks for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage site settings" on public.site_settings;
create policy "authenticated manage site settings" on public.site_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "public read website assets" on storage.objects;
create policy "public read website assets" on storage.objects for select using (bucket_id = 'website-assets');
drop policy if exists "authenticated upload website assets" on storage.objects;
create policy "authenticated upload website assets" on storage.objects for insert with check (bucket_id = 'website-assets' and auth.role() = 'authenticated');
drop policy if exists "authenticated update website assets" on storage.objects;
create policy "authenticated update website assets" on storage.objects for update using (bucket_id = 'website-assets' and auth.role() = 'authenticated');
