-- Run this in Supabase > SQL Editor > New query > Run

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text,
  year int default extract(year from now()),
  type text default 'News',
  created_at timestamptz default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  year int default extract(year from now()),
  type text default 'Photo',
  created_at timestamptz default now()
);

create table if not exists public.careers (
  id bigint generated by default as identity primary key,
  title text not null,
  department text,
  location text,
  type text default 'Full Time',
  description text not null,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.news enable row level security;
alter table public.gallery enable row level security;
alter table public.careers enable row level security;

-- Re-create policies safely.
drop policy if exists "Public can read news" on public.news;
drop policy if exists "Public can read gallery" on public.gallery;
drop policy if exists "Public can read careers" on public.careers;
drop policy if exists "Authenticated can manage news" on public.news;
drop policy if exists "Authenticated can manage gallery" on public.gallery;
drop policy if exists "Authenticated can manage careers" on public.careers;

-- Public visitors can read website content.
create policy "Public can read news" on public.news for select using (true);
create policy "Public can read gallery" on public.gallery for select using (true);
create policy "Public can read careers" on public.careers for select using (true);

-- Only logged-in Supabase admin users can add/edit/delete.
create policy "Authenticated can manage news" on public.news for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Authenticated can manage gallery" on public.gallery for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Authenticated can manage careers" on public.careers for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
