create table if not exists public.cms_blocks (
  id text primary key,
  page text not null,
  label text not null,
  type text not null default 'textarea',
  value text not null default '',
  style jsonb default '{}'::jsonb,
  is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.site_settings (
  id text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  date text default '',
  day text default '',
  month text default '',
  year int default extract(year from now()),
  type text default 'press-releases',
  image_url text default '',
  source_url text default '',
  is_featured boolean default false,
  is_published boolean default true,
  sort_order int default 10,
  created_at timestamptz default now()
);

create table if not exists public.careers (
  id bigint generated by default as identity primary key,
  title text not null,
  department text default '',
  location text default '',
  type text default '',
  description text default '',
  responsibilities text[] default '{}',
  requirements text[] default '{}',
  application_email text default '',
  is_active boolean default true,
  sort_order int default 10,
  created_at timestamptz default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  caption text default '',
  image_url text not null default '',
  category text default 'corporate',
  date text default '',
  is_published boolean default true,
  sort_order int default 10,
  created_at timestamptz default now()
);

insert into storage.buckets (id, name, public)
values ('cms-assets', 'cms-assets', true)
on conflict (id) do update set public = true;

create policy if not exists "Public read cms assets"
on storage.objects for select
using (bucket_id = 'cms-assets');

create policy if not exists "Authenticated upload cms assets"
on storage.objects for insert
to authenticated
with check (bucket_id = 'cms-assets');

create policy if not exists "Authenticated update cms assets"
on storage.objects for update
to authenticated
using (bucket_id = 'cms-assets')
with check (bucket_id = 'cms-assets');

create policy if not exists "Authenticated delete cms assets"
on storage.objects for delete
to authenticated
using (bucket_id = 'cms-assets');

alter table public.cms_blocks enable row level security;
alter table public.site_settings enable row level security;
alter table public.news enable row level security;
alter table public.careers enable row level security;
alter table public.gallery enable row level security;

create policy if not exists "Public read cms_blocks" on public.cms_blocks for select using (true);
create policy if not exists "Public read site_settings" on public.site_settings for select using (true);
create policy if not exists "Public read news" on public.news for select using (true);
create policy if not exists "Public read careers" on public.careers for select using (true);
create policy if not exists "Public read gallery" on public.gallery for select using (true);

create policy if not exists "Authenticated manage cms_blocks" on public.cms_blocks for all to authenticated using (true) with check (true);
create policy if not exists "Authenticated manage site_settings" on public.site_settings for all to authenticated using (true) with check (true);
create policy if not exists "Authenticated manage news" on public.news for all to authenticated using (true) with check (true);
create policy if not exists "Authenticated manage careers" on public.careers for all to authenticated using (true) with check (true);
create policy if not exists "Authenticated manage gallery" on public.gallery for all to authenticated using (true) with check (true);
