-- JETAMA Website CMS Backend Schema
-- Run this in Supabase SQL Editor.

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  date text default '',
  day text default '',
  month text default '',
  year int default extract(year from now()),
  type text default 'press-releases' check (type in ('gallery','videos','press-releases','announcement')),
  image_url text default '',
  source_url text default '',
  is_featured boolean default false,
  is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.careers (
  id bigint generated by default as identity primary key,
  title text not null,
  department text default '',
  location text default 'Kota Kinabalu, Sabah',
  type text default 'Full Time',
  description text not null,
  responsibilities text[] default '{}',
  requirements text[] default '{}',
  application_email text default 'hr@jetama.com.my',
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  image_url text not null,
  category text default 'general',
  is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.cms_blocks (
  id text primary key,
  page text not null,
  label text not null,
  type text default 'textarea',
  value text default '',
  style jsonb default '{}',
  updated_at timestamptz default now()
);

create table if not exists public.site_settings (
  id text primary key default 'global',
  value jsonb not null,
  updated_at timestamptz default now()
);

alter table public.news enable row level security;
alter table public.careers enable row level security;
alter table public.gallery enable row level security;
alter table public.cms_blocks enable row level security;
alter table public.site_settings enable row level security;

-- Public website can read only published/active content.
drop policy if exists "public read published news" on public.news;
create policy "public read published news" on public.news for select using (is_published = true);
drop policy if exists "public read active careers" on public.careers;
create policy "public read active careers" on public.careers for select using (is_active = true);
drop policy if exists "public read published gallery" on public.gallery;
create policy "public read published gallery" on public.gallery for select using (is_published = true);
drop policy if exists "public read cms" on public.cms_blocks;
create policy "public read cms" on public.cms_blocks for select using (true);
drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings for select using (true);

-- Logged-in admin users can manage CMS content.
drop policy if exists "authenticated manage news" on public.news;
create policy "authenticated manage news" on public.news for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage careers" on public.careers;
create policy "authenticated manage careers" on public.careers for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage gallery" on public.gallery;
create policy "authenticated manage gallery" on public.gallery for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage cms" on public.cms_blocks;
create policy "authenticated manage cms" on public.cms_blocks for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "authenticated manage settings" on public.site_settings;
create policy "authenticated manage settings" on public.site_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
